# Generated by Django 4.0 on 2021-12-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('stock', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_variant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_one', to='product.productvariant')),
                ('product_variant_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_three', to='product.productvariant')),
                ('product_variant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_two', to='product.productvariant')),
            ],
        ),
    ]
